package DataDictionaryDSLLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Agregation_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new BetweenConstraint_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CanBeNull_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ComparesonConstraint_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ExclusiveSpecialization_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Field_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new InConstraint_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new InValue_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new NotNullConstraint_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new PredefinedDomen_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new Reference_Editor());
      case 11:
        return Collections.<ConceptEditor>singletonList(new Row_Editor());
      case 12:
        return Collections.<ConceptEditor>singletonList(new SemanticDomen_Editor());
      case 13:
        return Collections.<ConceptEditor>singletonList(new Set_Editor());
      case 14:
        return Collections.<ConceptEditor>singletonList(new Structure_Editor());
      case 15:
        return Collections.<ConceptEditor>singletonList(new StructureReference_Editor());
      case 16:
        return Collections.<ConceptEditor>singletonList(new StructureRepository_Editor());
      case 17:
        return Collections.<ConceptEditor>singletonList(new Table_Editor());
      case 18:
        return Collections.<ConceptEditor>singletonList(new UnexclusiveSpecialization_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new Reference_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new StructureReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b224578073b01L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691def413L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691fc535fL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f369202b9daL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b224578078449L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b22457807455dL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691defac0L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691e2b810L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691f9b4daL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c57e8bL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c6005eL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c3eed4L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f3691ebb512L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c07d59L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b224578073afdL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b22457808af51L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b224578073e21L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c3eec2L), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0xd2d707c97ae7ba8L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c6005eL), MetaIdFactory.conceptId(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x6f4b22457808af51L)).seal();
}
