package DataDictionaryDSLLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EnumDomens extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnumDomens() {
    super(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c46943L, "EnumDomens", "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1176255889972422979");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_INTEGER_0 = new EnumerationDescriptor.MemberDescriptor("INTEGER", "INTEGER", 0x1052e67ff6c46944L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1176255889972422980");
  private final EnumerationDescriptor.MemberDescriptor myMember_CHARACTER_0 = new EnumerationDescriptor.MemberDescriptor("CHARACTER", "CHARACTER", 0x1052e67ff6c46946L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1176255889972422982");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOGICAL_0 = new EnumerationDescriptor.MemberDescriptor("LOGICAL", "LOGICAL", 0x1052e67ff6c46949L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1176255889972422985");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATE_0 = new EnumerationDescriptor.MemberDescriptor("DATE", "DATE", 0x1052e67ff6c85ca7L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1176255889972681895");
  private final EnumerationDescriptor.MemberDescriptor myMember_DECIMAL_0 = new EnumerationDescriptor.MemberDescriptor("DECIMAL", "DECIMAL", 0x17622f36920a99b0L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1684961122014894512");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x1052e67ff6c46943L, 0x1052e67ff6c46944L, 0x1052e67ff6c46946L, 0x1052e67ff6c46949L, 0x1052e67ff6c85ca7L, 0x17622f36920a99b0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_INTEGER_0, myMember_CHARACTER_0, myMember_LOGICAL_0, myMember_DATE_0, myMember_DECIMAL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "INTEGER":
        return myMember_INTEGER_0;
      case "CHARACTER":
        return myMember_CHARACTER_0;
      case "LOGICAL":
        return myMember_LOGICAL_0;
      case "DATE":
        return myMember_DATE_0;
      case "DECIMAL":
        return myMember_DECIMAL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
