package DataDictionaryDSLLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EnumOperations extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnumOperations() {
    super(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f369202b9e2L, "EnumOperations", "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1684961122014378466");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Less_0 = new EnumerationDescriptor.MemberDescriptor("Less", "<", 0x11e31b8d1c097569L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1288904211232814441");
  private final EnumerationDescriptor.MemberDescriptor myMember_LessEqual_0 = new EnumerationDescriptor.MemberDescriptor("LessEqual", "<=", 0x11e31b8d1c09756aL, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1288904211232814442");
  private final EnumerationDescriptor.MemberDescriptor myMember_Equal_0 = new EnumerationDescriptor.MemberDescriptor("Equal", "=", 0x11e31b8d1c0975a3L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1288904211232814499");
  private final EnumerationDescriptor.MemberDescriptor myMember_Greater_0 = new EnumerationDescriptor.MemberDescriptor("Greater", ">", 0x11e31b8d1c0975a7L, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1288904211232814503");
  private final EnumerationDescriptor.MemberDescriptor myMember_GreaterEqual_0 = new EnumerationDescriptor.MemberDescriptor("GreaterEqual", ">=", 0x11e31b8d1c0975acL, "r:1cb3074c-56f2-4794-a3fe-4907548a0a91(DataDictionaryDSLLanguage.structure)/1288904211232814508");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L, 0x17622f369202b9e2L, 0x11e31b8d1c097569L, 0x11e31b8d1c09756aL, 0x11e31b8d1c0975a3L, 0x11e31b8d1c0975a7L, 0x11e31b8d1c0975acL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Less_0, myMember_LessEqual_0, myMember_Equal_0, myMember_Greater_0, myMember_GreaterEqual_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Less":
        return myMember_Less_0;
      case "LessEqual":
        return myMember_LessEqual_0;
      case "Equal":
        return myMember_Equal_0;
      case "Greater":
        return myMember_Greater_0;
      case "GreaterEqual":
        return myMember_GreaterEqual_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
